### ISSUE TITLE
Calculated column issue with division when dividend is zero

### ISSUE THREAD

**Issue by heswell** [finos/vuu#1224]
create a simple calculated column like this

`PctFilled:double:=FilledQty / Quantity`

expression returns Quantity when FilledQty is zero, should return zero.

**Comment by chrisjstevo** [comment]
On orders table I believe

**Comment by heswell** [comment]
Yes I was trying the above on Orders table.

Additional observation. If I group (say by ccy) and aggregate (sum) Quantity and FilledQty , the calculated column does not appear to be evaluated against the summed aggregation values on the group row.

**Comment by naleeha** [comment]
Conclusion on this discussion was that the first reported issue is the only one in scope to fix
where if filled qty is zero FilledQty / Quantity should return zero

We need to remove the hardcoding on the ui for this as workaround for the demo
