### ISSUE TITLE
Calculated column numeric sort issue

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1251]
### Steps to Reproduce:
1. Open table with numbers 
2. Created a calculated column 
3. Sort on calculated column

e.g. SIMUL Orders table, create percentage filled 

![image](https://github.com/finos/vuu/assets/148964225/3d59ecc5-3cef-4f4e-8286-8fa487775c41)

### Expected Result:
Sort on numeric values

### Actual Result:
Sort as if its by alpha-numeric

99
100
0
0

![image](https://github.com/finos/vuu/assets/148964225/f8920312-0b03-4130-b9da-bbafa1c0d2b6)

### Additional Context:
potentially server side sort for calculated column is treating it as a string?

**Comment by junaidzm13** [comment]
Looks like that's related to the integer division:

  - in the percent filled we're dividing integer columns so the result is an integer -> but we specify the data type to be double. So in sort it tries value.asInstanceOf[Double], which fails and therefore sort doesn't get applied.
  - if we do something like filledQuantity * 1.0 / quantity, it works fine.

How do you guys think we should handle this?
  1. One solution could be for the expression parser to take into account the column data type. Or easier solution is if we don't have any use-case for integer division we can treat all divisions as floating point divisions
  2. Second, we could use a proper numeric conversion to double when applying sorts, but this might make it hard to investigate issues i.e. why for instance 5/2 and 4/2 are treated the same by the sort. We can add error logs when applying such conversions as a work around but still.

**Comment by chrisjstevo** [comment]
So I think resolving the casts would be good (oops my fault!). There is a whole set of literature on when we should widen data types in programming languages, as you rightly point out, these two:
```scala
=4/2
=5/2
```
would necessitate different data types to hold the result even with both having integer inputs. We could probably get away for the sort with some sensible heuristics (for example any operation involving a double numeric value or involving a division operator always results in a double result.)

Would be interested in your thoughts as well as @rumakt and @naleeha. 

Chris

**Comment by naleeha** [comment]
I think defaulting all division result to floating point on the server side make sense. Seem to be what Excel does as well. 
If we were to cast the result back to int using `value.asInstanceOf[Int]`, it truncates the decimal part which may not be what the user want depending on the scenario. 

There is a secondary question of, once you have the calculated value, what do we want to display. 
We could make this ui concern with the double decimal format setting
![image](https://github.com/finos/vuu/assets/148964225/adcb5d64-0121-4233-aafb-b911c98a795c)

Excel seems to round up, e.g. 1.6 becomes 2 with 0 dp
Not sure what we do with our UI atm


I am a bit confused where the `integer` columns are in this case. Both Filled Qty and Quantity seem to be defiled as double in SIMUL Order table.

**Comment by chrisjstevo** [comment]
Yes, agreed. I think the display is catered for by Steve's UI widget as it forces them to consider the datatype (and therefore the accuracy.)
