### ISSUE TITLE
Bug with VUU Server option for adding customised login validator is not setting

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1315]
When using following builder syntax to register the custom login validator, VUU server does not use it but use the default login validator. 

 VuuSecurityOptions.apply()
                        .withLoginValidator(new MyCustomLoginValidator()),

Issue seem to be a bug in following:

See class VuuSecurityOptionsImpl

`
 override def withLoginValidator(tokenValidator: LoginTokenValidator): VuuSecurityOptions = this.copy(authenticator = authenticator)`

It should be using the passed in tokenValidator in the copy it returns.

**Comment by wendymiaoo** [comment]
Wendy will be working on this
