### ISSUE TITLE
Row Permission Filter should not return data when the check errors

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#1410]
If permission checking errors while performing the check, it is essential that data is hidden incase the user does not have the correct permission to view that data. This is an important security feature.

Currently default behavior for all filter is that if it errors, just don't apply the filter

**Comment by naleeha** [comment]
One option is to enforce it within the RowPermissinFilter so if there is any exception, return empty primary keys
Need to review how this work for virtualised table

**Comment by rumakt** [comment]
In case of an exception, i would not return empty primary keys but rather skip the particular key that throws exception and continue processing
