### ISSUE TITLE
PLEASE DELETE THE URL OF UBS

### ISSUE THREAD

**Issue by raf52071** [finos/vuu#1508]
Hi naleeha, 

I hope all goes well.

I am a member of Cyber Threat Intelligence Team of UBS. Some weeks ago we recieved that a URL of UBS was exposed in this Github account.

We have tried to discover who are you and your position to request if you can remove the URL , since it is an internal URL of UBS.  Without success.

In that case, we raise our request by here.  Please could you remove any information of UBS of your Github account?

Thank you very much, 
Kind regards, 
Raf

```[tasklist]
### Tasks
```

**Comment by naleeha** [comment]
The url on https://github.com/finos/vuu/issues/1053 has been removed. Thanks
