### ISSUE TITLE
When a component is removed from the UI (click x on top right) the viewport is disabled, should probably be removed

### ISSUE THREAD

**Issue by chrisjstevo** [finos/vuu#337]
## Bug Report
When a component (which is attached to a server side viewport) is removed by clicking the X on the screen, the server side viewport is set to .enabled = false. This will lead to an increase in the collection of viewports over time. 

### Steps to Reproduce:
 1. Open grid against viewport
 2. Remove grid
 3. 11:42:04.038 [nioEventLoopGroup-3-1] INFO  o.finos.vuu.core.CoreServerApiHander - View port disabled (log message will be written to console)

### Expected Result:
Viewport deleted on server side (removed from collections)

**Comment by heswell** [comment]
Should be fixed if you want to try. Its in main
