### ISSUE TITLE
sort fails on a calculated column

### ISSUE THREAD

**Issue by heswell** [finos/vuu#479]
We have some calculated columns, CREATE_VP is successful, correct data is returned for all calculated columns 

![Screenshot 2023-01-31 at 22 30 19](https://user-images.githubusercontent.com/40262/215898546-576f81dd-4d89-4b12-a405-a0e9a36e67fd.png)

Sort on notional, message looks ok, but server throws exception

![Screenshot 2023-01-31 at 22 34 23](https://user-images.githubusercontent.com/40262/215899115-acf6804d-3f34-48bf-80fa-dbb0b7cca197.png)

![Screenshot 2023-01-31 at 22 35 15](https://user-images.githubusercontent.com/40262/215899241-308db700-91fb-4dff-9abd-2f29781b6f67.png)

To reproduce from main...

run the ui library build
yarn 
yarn build

then start the showcase
yarn showcase

open the showcase at localhost:5173

navigate to Table/VuuDataTableCalculatedColumns
(http://127.0.0.1:5173/Table/VuuDataTableCalculatedColumns)

Tscroll right to see the calculated columns - sort on one of them

**Comment by chrisjstevo** [comment]
Fixed
