### ISSUE TITLE
Filter grammar allows the use of an ID in the "IN" clause, this is likely incorrect

### ISSUE THREAD

**Issue by chrisjstevo** [finos/vuu#526]
In the filter grammar we have the definition for atom of: 

```
atom : ID | INT | FLOAT | STRING | TRUE | FALSE;
```

which means that when we do IN clauses, it would be grammatically correct to specify something like this, (even if it's garbage). 

```
ric in [exchange, mic]
```

To resolve this we should split out the data types from ATOM, so we have something like: 

```
data : INT | FLOAT | STRING | TRUE | FALSE;
atom : ID | data;
```

then we could fix this:

```
term : atom ( operator atom)? | LPAREN or_expression RPAREN | atom operator LBRACK data (',' data)* RBRACK ;
```

**Comment by ddimtirov** [comment]
This is no longer true. Closing.
