### ISSUE TITLE
calculated column fails

### ISSUE THREAD

**Issue by heswell** [finos/vuu#668]
the following column expression
`=if(quantity=0, 0, min(1, filledQuantity / quantity))`

fails on server with error
line 1:43 no viable alternative at input 'if(quantity=0,0,min(1.0,filledQuantity/'

The parser seems to terminate the expression after the '/'

Thought maybe it was an issue with the '/' character itself and I would need to escape it, but this works more or less ok
`=filledQuantity / quantity`

(more or less because divide by zero cases obviously yield wrong results) 

this also fails 
`=(filledQuantity / quantity)`

**Comment by chrisjstevo** [comment]
Will take a look over weekend

**Comment by chrisjstevo** [comment]
Looking at the tests I think it's possible that min expects a literal column name rather than an expression but will confirm in test

**Comment by chrisjstevo** [comment]
Hmm just added this test case, it works.....

Are you doing this on the orders table...

    Scenario("Check bracketed Divide") {
      //check what happens when we submit garbage column names
      withCalculatedColumns(sampleRowsLotsOfNulls(), tableColumns,
        CalcColumn("qtyDivbid", "Double", "=(quantity / bid)"),
      ) {
        Table(
          ("orderId", "quantity", "ric", "tradeTime", "bid", "ask", "onMkt", "trader", "ccyCross", "vwapPerf", "qtyDivbid"),
          ("NYC-0004", null, "AAPL.L", 5L, 99.0, 101.5, false, null, "GBPUSD", -0.1234, Double.NaN),
          ("LDN-0001", 100L, "VOD.L", 2L, 99.0, 101.5, true, "chris", "GBPUSD", 1.1234, 1.0101010101010102),
          ("LDN-0002", 100L, "BT.L", 1L, 99.0, 101.01, true, "steve", "GBPUSD", 1.1234, 1.0101010101010102),
          ("LDN-0003", null, "VOD.L", 3L, 99.0, 101.3, true, "chris", "GBPUSD", 1.1234, Double.NaN),
          ("LDN-0008", 100L, "BT.L", 5L, 99.0, 106.0, true, "chris", "GBPUSD", 1.1234, 1.0101010101010102),
          ("NYC-0002", 100L, "VOD.L", 6L, 99.0, 102.0, false, null, "GBPUSD", 1.1234, 1.0101010101010102),
          ("NYC-0010", null, "VOD.L", 6L, 99.0, 110.0, true, "steve", "GBPUSD", 1.1234, Double.NaN),
          ("NYC-0011", null, "VOD/L", 6L, 99.0, 109.0, true, "steve", "GBPUSD", 1.1234, Double.NaN),
          ("NYC-0012", null, "VOD\\L", 6L, 99.0, 105.11, true, "steve", "GBPUSD", 1.1234, Double.NaN),
          ("NYC-0013", null, "VOD\\L", 6L, 99.0, 122.0, true, "rahúl", "$GBPUSD", 1.1234, Double.NaN)
        )
      }
    }

**Comment by chrisjstevo** [comment]
Fixed.
