### ISSUE TITLE
Remove the Map[key, treeKey] and replace this with a lambda capture of these two variables at the point the wrappedhandler is created. This may prove to be expensive in GC terms, we will need to test.

### ISSUE THREAD

**Issue by chrisjstevo** [finos/vuu#705]
## Feature Request

See #703 for details.

**Comment by keikeicheung** [comment]
Added TreeBenchmark

<img width="1034" alt="image" src="https://github.com/finos/vuu/assets/12475086/44cd4d39-b186-44d2-8db9-f490303e5d04">

**Comment by keikeicheung** [comment]
<img width="1046" alt="image" src="https://github.com/finos/vuu/assets/12475086/bfe87233-daa5-4675-8bb1-d40ed25dae42">
after removing the concurrent map

**Comment by keikeicheung** [comment]
changed treeing a column with all unique value (before only has 4 unique values)
