### ISSUE TITLE
UI layout saved in local storage becomes invalid

### ISSUE THREAD

**Issue by naleeha** [finos/vuu#987]
## UI loads a blank screen, this happens when ui layout saved in the local storage becomes invalid
Can be resolved by going to Chrome Dev tools > Application > Local storage > right-click on the relevant vuu url > clear

### Steps to Reproduce:
 1. Close all Tabs within VUU workspace
 2. Drag basket trading feature on to tab less workspace
 ![image](https://github.com/finos/vuu/assets/148964225/ab62b273-2cf8-4c4e-b848-d32f9a4094f0)
3. Close the basket trading tab. This triggers to save invalid layout as {"props":{}}

### Environment:
Saw this in the current main code 

### Additional Comment
One way to fix this is to generate a new tab if user closes the  last tab?

**Comment by heswell** [comment]
Should be fixed.
